const STRINGS = {
  ko: {
    heroTitle: '어떤 게임을 분석할까요?',
    heroSubtitle: 'Chess.com 유저네임을 입력하세요',
    usernamePlaceholder: 'Chess.com 유저네임',
    pgnPaste: 'PGN 붙여넣기',
    boardInput: '직접 입력',
    startReview: '분석 시작',
    myLibrary: 'My library',
    vault: 'Vault',
    archive: 'Archive',
    greetingTitle: '복습할 항목이 있어요',
    viewAll: '전체보기 →',
    vaultViewAll: 'Vault 전체보기',
    back: 'Back',
    moves: '기보',
    moveNumHeader: '#',
    whiteHeader: '백',
    blackHeader: '흑',
    noMovesYet: '아직 분석된 수가 없습니다.',
    analyzePosition: '✦ 이 포지션 분석하기',
    colorChoiceTitle: '어느 진영으로 플레이하셨나요?',
    chooseWhite: '백 (White)',
    chooseBlack: '흑 (Black)',
    settings: 'Settings',
    language: '언어',
    boardCoords: 'Board Coordinates',
    boardCoordsHint: '보드에 좌표(a-h, 1-8)를 표시합니다.',
    geminiCoach: 'Gemini AI Coach',
    geminiCoachHint: 'AI 분석(ON) 또는 테스트 데이터(OFF)를 전환합니다.',
    enterMoves: '수 입력',
    undo: 'Undo',
    cancel: 'Cancel',
    analyze: 'Analyze',
    whatToSave: '무엇을 저장할까요?',
    saveThisMove: '이 수 저장 (Vault)',
    saveEntireGame: '게임 전체 저장',
    titlePlayers: '제목 / 플레이어',
    titlePlayersPlaceholder: '예: Me vs Magnus',
    notesOptional: '메모 (선택)',
    notesGamePlaceholder: '멋진 공격 게임...',
    saveGame: '게임 저장',
    saveToVault: 'Vault에 저장',
    category: '분류',
    notesMoveplaceholder: '왜 이 수를 뒀나요? 최선의 수는?',
    saveMove: '수 저장',
    myVault: 'My Vault',
    savedGames: 'Saved Games',
    findBestMove: '최선의 수를 찾으세요',
    returnMainLine: '메인 라인으로 돌아가기',
    analyzing: '분석 중...',
  },
  en: {
    heroTitle: 'What game would you like to review?',
    heroSubtitle: 'Enter your Chess.com username',
    usernamePlaceholder: 'Chess.com username',
    pgnPaste: 'Paste PGN',
    boardInput: 'Play on board',
    startReview: 'Start Review',
    myLibrary: 'My library',
    vault: 'Vault',
    archive: 'Archive',
    greetingTitle: 'You have items to review',
    viewAll: 'View all →',
    vaultViewAll: 'View all in Vault',
    back: 'Back',
    moves: 'Moves',
    moveNumHeader: '#',
    whiteHeader: 'White',
    blackHeader: 'Black',
    noMovesYet: 'No moves analyzed yet.',
    analyzePosition: '✦ Analyze this position',
    colorChoiceTitle: 'Which side did you play?',
    chooseWhite: 'White',
    chooseBlack: 'Black',
    settings: 'Settings',
    language: 'Language',
    boardCoords: 'Board Coordinates',
    boardCoordsHint: 'Show algebraic coordinates on the board.',
    geminiCoach: 'Gemini AI Coach',
    geminiCoachHint: 'Toggle real AI analysis (ON) or test data (OFF).',
    enterMoves: 'Enter Moves',
    undo: 'Undo',
    cancel: 'Cancel',
    analyze: 'Analyze',
    whatToSave: 'What to save?',
    saveThisMove: 'Save This Move (Vault)',
    saveEntireGame: 'Save Entire Game',
    titlePlayers: 'Title / Players',
    titlePlayersPlaceholder: 'e.g. Me vs Magnus',
    notesOptional: 'Notes (Optional)',
    notesGamePlaceholder: 'Great attacking game...',
    saveGame: 'Save Game',
    saveToVault: 'Save to Vault',
    category: 'Category',
    notesMoveplaceholder: 'Why did you play this? What was the right move?',
    saveMove: 'Save Move',
    myVault: 'My Vault',
    savedGames: 'Saved Games',
    findBestMove: 'Find Best Move',
    returnMainLine: 'Return to Main Line',
    analyzing: 'Analyzing...',
  },
};

let locale = localStorage.getItem('locale') || 'ko';
export const t = (key) => STRINGS[locale]?.[key] ?? STRINGS['ko']?.[key] ?? key;
export const setLocale = (lang) => {
  locale = lang;
  localStorage.setItem('locale', lang);
};
export const getLocale = () => locale;
