const STRINGS = {
  ko: {
    heroTitle: '어떤 게임을 분석할까요?',
    heroSubtitle: 'Chess.com 유저네임을 입력하세요',
    usernamePlaceholder: 'Chess.com 유저네임',
    manualInput: '수 입력',
    archive_vault_btn: '복기',
    archive_saved_games_btn: '저장된 게임',
    vault_title: '복기',
    vault_empty: '저장된 항목이 없습니다',
    vault_count: '{count}개 저장됨',
    vault_delete_confirm: '이 저장된 수를 삭제할까요?',
    vault_legacy_error: '이전 버전의 저장 데이터로 열 수 없습니다. 삭제해주세요.',
    vault_pgn_error: '저장된 PGN을 불러올 수 없습니다.',
    vault_start: '시작',
    vault_list_link: '목록',
    vault_list_title: '목록',
    vault_blunder_list_empty: '아직 항목이 없어요',
    vault_blunder_list_empty_mistake: '블런더가 아직 없어요',
    vault_blunder_list_empty_mate: '놓친 메이트가 아직 없어요',
    vault_blunder_list_empty_other: '기타 항목이 아직 없어요',
    vault_puzzle_empty: '분석을 돌리면 자동으로 모여요',
    vault_puzzle_empty_mistake: '블런더 풀이가 아직 없어요',
    vault_puzzle_empty_mate: '놓친 메이트가 아직 없어요',
    vault_puzzle_empty_other: '저장된 포지션이 아직 없어요',
    vault_filter_mistake: '블런더',
    vault_filter_mate: '메이트',
    vault_filter_other: '기타',
    vault_puzzle_other_header: '저장된 포지션',
    vault_puzzle_other_subhead: '풀이 없이 보기',
    vault_puzzle_find_best: '최선수를 찾으세요',
    vault_puzzle_find_mate: '메이트를 찾으세요',
    vault_puzzle_correct: '정답',
    vault_puzzle_incorrect: '오답',
    vault_puzzle_mate_solved: '메이트!',
    vault_puzzle_you_played: '둔 수',
    vault_puzzle_best: '정답수',
    vault_puzzle_mate_label: '놓친 메이트',
    vault_puzzle_next: '다음',
    vault_puzzle_retry: '다시 풀기',
    vault_puzzle_restart: '처음부터',
    tab_engine: 'Engine',
    tab_ai: 'AI',
    vault_engine_suggested: '엔진 추천: {move}',
    vault_delete_title: '삭제',
    vault_delete_btn: '삭제',
    saved_games_count: '{count}개 저장됨',
    saved_games_empty: '저장된 게임이 없습니다',
    saved_games_category_label: '카테고리',
    saved_games_cat_my_game: '내 실전 게임',
    saved_games_cat_otb: '오프라인 게임',
    saved_games_cat_opening: '오프닝 연구',
    saved_games_cat_pro: '프로 기보',
    saved_games_filter_all: '전체',
    home_filter_rapid: '래피드',
    home_filter_blitz: '블리츠',
    home_filter_bullet: '불렛',
    saved_games_delete_confirm: '이 저장된 게임을 삭제할까요?',
    saved_games_default_title: '저장된 게임',
    saved_games_untitled: '제목 없는 게임',
    saved_games_saved: '저장됐어요!',
    saved_games_edit: '수정',
    saved_games_delete: '삭제',
    back: 'Back',
    moves: '기보',
    moveNumHeader: '#',
    whiteHeader: '백',
    blackHeader: '흑',
    noMovesYet: '아직 분석된 수가 없습니다.',
    analyzePosition: '✦ 이 포지션 분석하기',
    colorChoiceTitle: '어느 진영으로 플레이하셨나요?',
    chooseWhite: '백 (White)',
    chooseBlack: '흑 (Black)',
    settings: 'Settings',
    home_feedback: '피드백',
    home_settings: '설정',
    nav_home: '홈',
    nav_vault: '복기',
    nav_saved: '저장',
    nav_insights: '통계',
    report_accuracy: '정확도',
    insights_title: '통계',
    insights_subtitle_n: '최근 {n}게임 기준',
    insights_subtitle_filtered: '최근 {total}게임 중 {label} {n}개',
    insights_total_n: '총 {n}게임',
    insights_winrate: '승률',
    insights_wins: '승',
    insights_draws: '무',
    insights_losses: '패',
    insights_w: 'W',
    insights_d: 'D',
    insights_l: 'L',
    insights_by_color: '색깔별 성적',
    insights_white: '백',
    insights_black: '흑',
    insights_by_tc: '시간제어별 성적',
    insights_top_openings: '자주 두는 오프닝',
    insights_termination: '게임 종료 사유',
    insights_term_checkmate: '체크메이트',
    insights_term_resign: '리사인',
    insights_term_timeout: '시간패',
    insights_term_draw: '무승부',
    insights_term_abandon: '기권/이탈',
    insights_game_length: '게임 길이',
    insights_len_short: '20수 미만',
    insights_len_medium: '20–39수',
    insights_len_long: '40–59수',
    insights_len_marathon: '60수 이상',
    insights_time_of_day: '시간대별 성적',
    insights_tod_morning: '아침 (5–12시)',
    insights_tod_afternoon: '낮 (12–18시)',
    insights_tod_evening: '저녁 (18–23시)',
    insights_tod_night: '밤 (23–5시)',
    // 요일별
    insights_day_of_week: '요일별 성적',
    insights_dow_mon: '월요일',
    insights_dow_tue: '화요일',
    insights_dow_wed: '수요일',
    insights_dow_thu: '목요일',
    insights_dow_fri: '금요일',
    insights_dow_sat: '토요일',
    insights_dow_sun: '일요일',
    // 상대 레이팅 차이
    insights_opp_diff: '상대 레이팅별 성적',
    insights_opp_much_lower: '나보다 200↓',
    insights_opp_lower: '나보다 50–200↓',
    insights_opp_similar: '비슷한 레벨',
    insights_opp_higher: '나보다 50–200↑',
    insights_opp_much_higher: '나보다 200↑',
    // 첫 수
    insights_first_move: '첫 수 (백)',
    insights_first_move_other: '기타',
    // 캐슬링
    insights_castling: '캐슬링 패턴',
    insights_castle_king: '킹사이드 (O-O)',
    insights_castle_queen: '퀸사이드 (O-O-O)',
    insights_castle_none: '캐슬 안 함',
    // 거래 활동
    insights_trade_activity: '거래 활동 (캡쳐 비율)',
    insights_trade_sub: '캡쳐 {cap}/{total}수',
    insights_trade_passive: '소극적',
    insights_trade_balanced: '균형',
    insights_trade_active: '활발',
    insights_trade_aggressive: '공격적',
    // 자주 만난 상대
    insights_top_opponents: '자주 만난 상대',
    // 레이팅 변화
    insights_rating_change: '레이팅 변화',
    insights_rating_sub: '{n}게임 · {start} → {end}',
    insights_rating_range: '최고 {peak} · 최저 {trough}',
    // 블런더 핫스팟
    insights_blunder_hotspots: '블런더 자주 나오는 수 번호',
    // 카테고리 탭
    insights_cat_summary: '요약',
    insights_cat_opening: '오프닝',
    insights_cat_clock: '시계',
    insights_cat_when: '시간',
    insights_cat_people: '사람',
    insights_cat_weak: '약점',
    insights_empty: '데이터 없음',
    insights_no_games: '아직 분석할 게임이 없습니다.',
    insights_need_username: 'Chess.com 유저네임을 먼저 입력해주세요.',
    insights_fetch_error: '게임을 불러오지 못했습니다. 잠시 후 다시 시도해주세요.',
    insights_time_unit_sec: '초',
    insights_time_unit_min: '분',
    insights_time_no_clock: '시계 데이터가 있는 게임이 없습니다.',
    insights_avg_think: '평균 사고 시간',
    insights_avg_think_sub: '{games}게임 · {moves}수 기준',
    insights_phase_time: '단계별 사고 시간',
    insights_phase_opening: '오프닝 (1–10수)',
    insights_phase_middle: '미들게임 (11–30수)',
    insights_phase_end: '엔드게임 (31수+)',
    insights_time_pressure: '시간 압박',
    insights_time_pressure_sub: '잔여 ≤10초로 둔 수 {n}/{total}',
    insights_instant: '즉답 비율',
    insights_instant_sub: '3초 안에 둔 수 {n}/{total}',
    // 비교/연승/narrative
    insights_delta_unit: '%p',
    insights_streak_current_w: '현재 {n}연승',
    insights_streak_current_l: '현재 {n}연패',
    insights_streak_best_w: '최장 {n}연승',
    insights_narr_trend_up: '최근 {n}게임 승률이 그 전 {n}게임보다 {d}%p 높아요',
    insights_narr_trend_down: '최근 {n}게임 승률이 그 전 {n}게임보다 {d}%p 낮아요',
    insights_narr_white_strong: '백 승률이 흑보다 {d}%p 높아요',
    insights_narr_black_strong: '흑 승률이 백보다 {d}%p 높아요',
    insights_narr_time_pressure: '잔여 10초 이하에서 둔 수가 {pct}%',
    insights_narr_instant: '3초 안에 둔 수가 {pct}%',
    insights_narr_timeout: '게임 종료의 {pct}%가 시간패',
    // 결과 흐름 (streakiness)
    insights_flow_title: '결과 흐름',
    insights_flow_streaky: '연승/연패형',
    insights_flow_alternating: '교차형',
    insights_flow_neutral: '균형형',
    insights_flow_sub: '결과 연속 {actual}% · 무작위 기대 {expected}%',
    insights_flow_extremes: '최장 {w}연승 · 최장 {l}연패',
    insights_flow_extremes_w_only: '최장 {w}연승',
    insights_flow_extremes_l_only: '최장 {l}연패',
    aria_settings: '설정',
    aria_search: '검색',
    aria_new_analysis: '수 입력',
    settings_depth: '엔진 분석 깊이',
    settings_depth_hint: '기본 14. 저사양 모바일은 12, PC는 16 이상도 OK. 높을수록 정확하지만 느려집니다.',
    language: '언어',
    boardCoords: 'Board Coordinates',
    boardCoordsHint: '보드에 좌표(a-h, 1-8)를 표시합니다.',
    geminiCoach: 'Gemini AI Coach',
    geminiCoachHint: 'AI 분석(ON) 또는 테스트 데이터(OFF)를 전환합니다.',
    cancel: 'Cancel',
    whatToSave: '무엇을 저장할까요?',
    saveThisMove: '이 수 저장 (복기)',
    saveEntireGame: '게임 전체 저장',
    titlePlayers: '제목 / 플레이어',
    titlePlayersPlaceholder: '예: Me vs Magnus',
    notesOptional: '메모 (선택)',
    notesGamePlaceholder: '멋진 공격 게임...',
    saveGame: '게임 저장',
    saveToVault: '복기에 저장',
    category: '분류',
    notes_move_placeholder: '왜 이 수를 뒀나요? 최선의 수는?',
    saveMove: '수 저장',
    savedGames: 'Saved Games',
    returnMainLine: '메인 라인으로 돌아가기',
    analysis_start_btn: '분석 시작',
    analysis_no_moves: '수를 하나 이상 두거나 PGN을 붙여넣어 주세요.',
    analysis_no_save_start: '시작 포지션은 저장할 수 없습니다.',
    analysis_invalid_pgn: '올바르지 않은 PGN 또는 수 형식입니다.',
    preview_moves: '{n}수',
    games_loading: '게임 불러오는 중...',
    games_fetching: '최근 게임 가져오는 중...',
    games_fetch_error: '게임을 불러오지 못했습니다.',
    game_no_pgn: '이 게임의 PGN을 불러올 수 없습니다.',
    game_result_win: '승',
    game_result_loss: '패',
    game_result_draw: '무',
    ui_review: '리뷰',
    ui_engine_hint: '길게 눌러 미리보기 · 탭하여 시뮬레이션',
    gemini_no_start: '시작 위치에서는 AI 해설을 사용할 수 없습니다. 체스 수를 하나 선택해 주세요.',
    gemini_no_free: '자유 탐색 모드에서는 지원하지 않습니다. 메인 기보로 돌아가 주세요.',
    gemini_analyzing: 'AI가 국면을 분석하고 있습니다...',
    gemini_analyzing_sub: '(약 2~5초 소요)',
    gemini_error: 'AI 해설을 불러오는 데 실패했습니다.',
    gemini_already_best: '이미 훌륭한 수입니다',
    gemini_best_only: 'AI 코치는 Blunder·Mistake 등 설명이 꼭 필요한 상황에서만 분석합니다.',
    feedback_title: '피드백',
    feedback_send: '전송',
    feedback_validation: '내용을 입력해주세요.',
    feedback_sending: '전송 중...',
    feedback_success: '소중한 피드백 감사합니다!',
    feedback_error_label: '전송 실패',
    feedback_error_network: '네트워크 오류가 발생했습니다.',
    input_title: '수 입력',
    input_undo: '실행 취소',
    input_analyze: '분석 시작 →',
    onboarding_tagline: '당신의 블런더와 놓친 메이트를 기억합니다',
    onboarding_label: 'Chess.com 아이디를 입력하세요',
    onboarding_skip: '건너뛰기',
    home_search_other: '다른 유저 검색',
    home_recent_games: '최근 게임',
    home_other_user_games: '@{username} 게임',
    home_back_to_my_games: '내 게임으로 돌아가기',
    settings_logout: '로그아웃',
    settings_logout_confirm: '로그아웃하시겠습니까? 내 계정 정보가 초기화되고 온보딩 화면으로 돌아갑니다. (저장된 복기/게임은 유지됩니다)',
    settings_about: '이 앱에 대해',
    about_title: 'Blundermate',
    about_desc: '체스 게임 리뷰 웹앱. PGN 또는 Chess.com에서 게임을 불러와 Stockfish 분석과 Gemini 한국어 해설을 제공합니다.',
    about_repo: 'GitHub',
    about_license_label: '라이선스',
    about_license_value: 'GNU GPL v3.0',
    about_credits: '오픈소스',
    about_credits_intro: '본 프로젝트는 다음 오픈소스 프로젝트를 기반으로 합니다.',
    about_credit_freechess_note: '수 분류 알고리즘 포팅',
    report_move_classification: '수 분류',
    report_white: '백',
    report_black: '흑',
    report_you: '나',
    review_view: '리뷰 보기',
    review_eval_over_time: '수별 평가',
    review_move_quality: '수 분류',
    review_game_overview: '게임 개요',
    report_win_chance: '승률 변화',
    report_empty: '분석 데이터가 아직 없습니다',
    class_brilliant: 'Brilliant',
    class_great: 'Great',
    class_best: 'Best',
    class_excellent: 'Excellent',
    class_good: 'Good',
    class_inaccuracy: 'Inaccuracy',
    class_mistake: 'Mistake',
    class_blunder: 'Blunder',
    class_forced: 'Forced',
    start_review_from_first: '첫 수부터 복기 →',
    dateToday: '오늘',
    dateYesterday: '어제',
    dateDaysAgo: '{n}일 전',
    moves_suffix: '수',
    copyPgn: 'PGN 복사',
    copied: '복사됨!',
    ratingRapid: 'Rapid',
    ratingBlitz: 'Blitz',
    ratingBullet: 'Bullet',
    noRating: '—',
    profile_record_label: '최근 15경기',
    profile_record_win_short: '승',
    profile_record_loss_short: '패',
    profile_record_draw_short: '무',
    tier_pawn: '폰',
    tier_knight: '나이트',
    tier_bishop: '비숍',
    tier_rook: '룩',
    tier_queen: '퀸',
    tier_king: '킹',
    tier_emperor: '황제',
    tier_unranked: '언랭크',
    tier_modal_title: '랭크 시스템',
    tier_modal_intro: 'Blundermate에서 사용하는 랭크 체계예요. Chess.com 래피드 레이팅 기준입니다.',
    tier_range_open: '{min} 이상',
    tier_range_closed: '{min} – {max}',
    analysis_variation: '변이 분석 중...',
    analysis_exploring: '포지션 탐색 중...',
    analysis_loading: '로딩중입니다...',
    sim_start: '시작',
    input_placeholder: 'PGN 또는 FEN을 붙여넣거나 보드에서 수를 입력하세요',
    input_reset: '처음부터',
    filter_no_games: '표시할 게임이 없습니다',
    time_min: '{n}분',
    time_sec: '{n}초',
  },
  en: {
    heroTitle: 'What game would you like to review?',
    heroSubtitle: 'Enter your Chess.com username',
    usernamePlaceholder: 'Chess.com username',
    manualInput: 'Enter Moves',
    archive_vault_btn: 'Vault',
    archive_saved_games_btn: 'Saved Games',
    vault_title: 'Vault',
    vault_empty: 'Your Vault is empty. Analyze some games and save your mistakes!',
    vault_count: '{count} saved',
    vault_delete_confirm: 'Delete this saved move from your Vault?',
    vault_legacy_error: 'This saved move is from an older version and cannot be opened. Please delete it.',
    vault_pgn_error: 'Saved PGN could not be parsed.',
    vault_start: 'Start',
    vault_list_link: 'List',
    vault_list_title: 'List',
    vault_blunder_list_empty: 'Nothing here yet',
    vault_blunder_list_empty_mistake: 'No mistakes yet',
    vault_blunder_list_empty_mate: 'No missed mates yet',
    vault_blunder_list_empty_other: 'No saved positions yet',
    vault_puzzle_empty: 'Analyze games to fill this list automatically',
    vault_puzzle_empty_mistake: 'No mistake puzzles yet',
    vault_puzzle_empty_mate: 'No missed-mate puzzles yet',
    vault_puzzle_empty_other: 'No saved positions yet',
    vault_filter_mistake: 'Mistakes',
    vault_filter_mate: 'Mates',
    vault_filter_other: 'Other',
    vault_puzzle_other_header: 'Saved position',
    vault_puzzle_other_subhead: 'Browse only',
    vault_puzzle_find_best: 'Find the best move',
    vault_puzzle_find_mate: 'Find the mate',
    vault_puzzle_correct: 'Correct',
    vault_puzzle_incorrect: 'Incorrect',
    vault_puzzle_mate_solved: 'Mate!',
    vault_puzzle_you_played: 'You played',
    vault_puzzle_best: 'Best',
    vault_puzzle_mate_label: 'Missed mate',
    vault_puzzle_next: 'Next',
    vault_puzzle_retry: 'Try again',
    vault_puzzle_restart: 'Start over',
    tab_engine: 'Engine',
    tab_ai: 'AI',
    vault_engine_suggested: 'Engine suggested: {move}',
    vault_delete_title: 'Delete',
    vault_delete_btn: 'Delete',
    saved_games_count: '{count} saved',
    saved_games_empty: 'No saved games',
    saved_games_category_label: 'Category',
    saved_games_cat_my_game: 'My Game',
    saved_games_cat_otb: 'OTB Game',
    saved_games_cat_opening: 'Opening Study',
    saved_games_cat_pro: 'Pro Game',
    saved_games_filter_all: 'All',
    home_filter_rapid: 'Rapid',
    home_filter_blitz: 'Blitz',
    home_filter_bullet: 'Bullet',
    saved_games_delete_confirm: 'Delete this saved game?',
    saved_games_default_title: 'Saved Game',
    saved_games_untitled: 'Untitled Game',
    saved_games_saved: 'Saved!',
    saved_games_edit: 'Edit',
    saved_games_delete: 'Delete',
    back: 'Back',
    moves: 'Moves',
    moveNumHeader: '#',
    whiteHeader: 'White',
    blackHeader: 'Black',
    noMovesYet: 'No moves analyzed yet.',
    analyzePosition: '✦ Analyze this position',
    colorChoiceTitle: 'Which side did you play?',
    chooseWhite: 'White',
    chooseBlack: 'Black',
    settings: 'Settings',
    home_feedback: 'Feedback',
    home_settings: 'Settings',
    nav_home: 'Home',
    nav_vault: 'Vault',
    nav_saved: 'Saved',
    nav_insights: 'Insights',
    report_accuracy: 'Accuracy',
    insights_title: 'Insights',
    insights_subtitle_n: 'Based on last {n} games',
    insights_subtitle_filtered: 'Last {total} games · {label} {n}',
    insights_total_n: '{n} games total',
    insights_winrate: 'Win rate',
    insights_wins: 'Wins',
    insights_draws: 'Draws',
    insights_losses: 'Losses',
    insights_w: 'W',
    insights_d: 'D',
    insights_l: 'L',
    insights_by_color: 'By color',
    insights_white: 'White',
    insights_black: 'Black',
    insights_by_tc: 'By time control',
    insights_top_openings: 'Top openings',
    insights_termination: 'How games ended',
    insights_term_checkmate: 'Checkmate',
    insights_term_resign: 'Resignation',
    insights_term_timeout: 'Timeout',
    insights_term_draw: 'Draw',
    insights_term_abandon: 'Abandoned',
    insights_game_length: 'Game length',
    insights_len_short: 'Under 20 moves',
    insights_len_medium: '20–39 moves',
    insights_len_long: '40–59 moves',
    insights_len_marathon: '60+ moves',
    insights_time_of_day: 'Time of day',
    insights_tod_morning: 'Morning (5–12)',
    insights_tod_afternoon: 'Afternoon (12–18)',
    insights_tod_evening: 'Evening (18–23)',
    insights_tod_night: 'Night (23–5)',
    // Day of week
    insights_day_of_week: 'By day of week',
    insights_dow_mon: 'Monday',
    insights_dow_tue: 'Tuesday',
    insights_dow_wed: 'Wednesday',
    insights_dow_thu: 'Thursday',
    insights_dow_fri: 'Friday',
    insights_dow_sat: 'Saturday',
    insights_dow_sun: 'Sunday',
    // Opponent rating diff
    insights_opp_diff: 'By opponent strength',
    insights_opp_much_lower: '200+ below',
    insights_opp_lower: '50–200 below',
    insights_opp_similar: 'Similar level',
    insights_opp_higher: '50–200 above',
    insights_opp_much_higher: '200+ above',
    // First move
    insights_first_move: 'First move (white)',
    insights_first_move_other: 'Other',
    // Castling
    insights_castling: 'Castling pattern',
    insights_castle_king: 'Kingside (O-O)',
    insights_castle_queen: 'Queenside (O-O-O)',
    insights_castle_none: 'Did not castle',
    // Trade activity
    insights_trade_activity: 'Trade activity (capture rate)',
    insights_trade_sub: '{cap} captures / {total} moves',
    insights_trade_passive: 'Passive',
    insights_trade_balanced: 'Balanced',
    insights_trade_active: 'Active',
    insights_trade_aggressive: 'Aggressive',
    // Top opponents
    insights_top_opponents: 'Most-faced opponents',
    // Rating change
    insights_rating_change: 'Rating change',
    insights_rating_sub: '{n} games · {start} → {end}',
    insights_rating_range: 'Peak {peak} · Low {trough}',
    // Blunder hotspots
    insights_blunder_hotspots: 'Blunders by move number',
    // Category tabs
    insights_cat_summary: 'Summary',
    insights_cat_opening: 'Openings',
    insights_cat_clock: 'Clock',
    insights_cat_when: 'When',
    insights_cat_people: 'People',
    insights_cat_weak: 'Weak spots',
    insights_empty: 'No data',
    insights_no_games: 'No games to analyze yet.',
    insights_need_username: 'Please enter your Chess.com username first.',
    insights_fetch_error: 'Failed to load games. Please try again later.',
    insights_time_unit_sec: 's',
    insights_time_unit_min: 'm',
    insights_time_no_clock: 'No games with clock data.',
    insights_avg_think: 'Average think time',
    insights_avg_think_sub: '{games} games · {moves} moves',
    insights_phase_time: 'Time per phase',
    insights_phase_opening: 'Opening (1–10)',
    insights_phase_middle: 'Middlegame (11–30)',
    insights_phase_end: 'Endgame (31+)',
    insights_time_pressure: 'Time pressure',
    insights_time_pressure_sub: 'Moves with ≤10s left: {n}/{total}',
    insights_instant: 'Instant moves',
    insights_instant_sub: 'Played in <3s: {n}/{total}',
    insights_delta_unit: 'pp',
    insights_streak_current_w: '{n}-game win streak',
    insights_streak_current_l: '{n}-game losing streak',
    insights_streak_best_w: 'Best win streak: {n}',
    insights_narr_trend_up: "Recent {n}-game win rate is {d}pp higher than the prior {n}",
    insights_narr_trend_down: "Recent {n}-game win rate is {d}pp lower than the prior {n}",
    insights_narr_white_strong: 'White wins {d}pp more often than Black',
    insights_narr_black_strong: 'Black wins {d}pp more often than White',
    insights_narr_time_pressure: '{pct}% of moves played with under 10s left',
    insights_narr_instant: '{pct}% of moves played in under 3s',
    insights_narr_timeout: '{pct}% of games ended on time',
    insights_flow_title: 'Result flow',
    insights_flow_streaky: 'Streaky',
    insights_flow_alternating: 'Alternating',
    insights_flow_neutral: 'Balanced',
    insights_flow_sub: '{actual}% same as previous · {expected}% expected',
    insights_flow_extremes: 'Longest: {w}W · {l}L',
    insights_flow_extremes_w_only: 'Longest: {w}W',
    insights_flow_extremes_l_only: 'Longest: {l}L',
    aria_settings: 'Settings',
    aria_search: 'Search',
    aria_new_analysis: 'New Analysis',
    settings_depth: 'Engine Analysis Depth',
    settings_depth_hint: 'Default 14. Low-end mobile: 12, PC: 16+ also fine. Higher is more accurate but slower.',
    language: 'Language',
    boardCoords: 'Board Coordinates',
    boardCoordsHint: 'Show algebraic coordinates on the board.',
    geminiCoach: 'Gemini AI Coach',
    geminiCoachHint: 'Toggle real AI analysis (ON) or test data (OFF).',
    cancel: 'Cancel',
    whatToSave: 'What to save?',
    saveThisMove: 'Save This Move (Vault)',
    saveEntireGame: 'Save Entire Game',
    titlePlayers: 'Title / Players',
    titlePlayersPlaceholder: 'e.g. Me vs Magnus',
    notesOptional: 'Notes (Optional)',
    notesGamePlaceholder: 'Great attacking game...',
    saveGame: 'Save Game',
    saveToVault: 'Save to Vault',
    category: 'Category',
    notes_move_placeholder: 'Why did you play this? What was the right move?',
    saveMove: 'Save Move',
    savedGames: 'Saved Games',
    returnMainLine: 'Return to Main Line',
    analysis_start_btn: 'Start Analysis',
    analysis_no_moves: 'Please play at least one move or paste a PGN to analyze.',
    analysis_no_save_start: 'Cannot save the starting position.',
    analysis_invalid_pgn: 'Invalid PGN or move format. Please check your text.',
    preview_moves: '{n} moves',
    games_loading: 'Loading archives...',
    games_fetching: 'Fetching latest games...',
    games_fetch_error: 'Failed to fetch games.',
    game_no_pgn: 'This game has no PGN available.',
    game_result_win: 'Win',
    game_result_loss: 'Loss',
    game_result_draw: 'Draw',
    ui_review: 'Review',
    ui_engine_hint: 'hover to preview · click to simulate',
    gemini_no_start: 'AI analysis is not available at the starting position. Please select a move.',
    gemini_no_free: 'Not available in free exploration mode. Please return to the main line.',
    gemini_analyzing: 'AI is analyzing the position...',
    gemini_analyzing_sub: '(usually 2–5 seconds)',
    gemini_error: 'Failed to load AI analysis.',
    gemini_already_best: 'Already an excellent move',
    gemini_best_only: 'AI Coach only analyzes positions that need explanation, such as Blunders and Mistakes.',
    feedback_title: 'Feedback',
    feedback_send: 'Send',
    feedback_validation: 'Please enter a message.',
    feedback_sending: 'Sending...',
    feedback_success: 'Thank you for your feedback!',
    feedback_error_label: 'Send failed',
    feedback_error_network: 'A network error occurred.',
    input_title: 'Enter moves',
    input_undo: 'Undo',
    input_analyze: 'Start analysis →',
    onboarding_tagline: 'Remember your chess mistakes',
    onboarding_label: 'Enter your Chess.com username',
    onboarding_skip: 'Skip',
    home_search_other: 'Search another user',
    home_recent_games: 'Recent games',
    home_other_user_games: "@{username}'s games",
    home_back_to_my_games: 'Back to my games',
    settings_logout: 'Log out',
    settings_logout_confirm: 'Log out? Your account info will be reset and you will return to onboarding. (Saved Vault / Games will be kept)',
    settings_about: 'About this app',
    about_title: 'Blundermate',
    about_desc: 'A chess game review web app. Imports games from PGN or Chess.com, with Stockfish analysis and Gemini AI commentary.',
    about_repo: 'GitHub',
    about_license_label: 'License',
    about_license_value: 'GNU GPL v3.0',
    about_credits: 'Open source',
    about_credits_intro: 'Built on the following open-source projects.',
    about_credit_freechess_note: 'Move classification algorithm port',
    report_move_classification: 'Move Classification',
    report_white: 'White',
    report_black: 'Black',
    report_you: 'YOU',
    review_view: 'Review',
    review_eval_over_time: 'Evaluation over time',
    review_move_quality: 'Move Quality',
    review_game_overview: 'Game Overview',
    report_win_chance: 'Win Chance',
    report_empty: 'No analysis data yet',
    class_brilliant: 'Brilliant',
    class_great: 'Great',
    class_best: 'Best',
    class_excellent: 'Excellent',
    class_good: 'Good',
    class_inaccuracy: 'Inaccuracy',
    class_mistake: 'Mistake',
    class_blunder: 'Blunder',
    class_forced: 'Forced',
    start_review_from_first: 'Start review →',
    dateToday: 'Today',
    dateYesterday: 'Yesterday',
    dateDaysAgo: '{n}d ago',
    moves_suffix: ' moves',
    copyPgn: 'Copy PGN',
    copied: 'Copied!',
    ratingRapid: 'Rapid',
    ratingBlitz: 'Blitz',
    ratingBullet: 'Bullet',
    noRating: '—',
    profile_record_label: 'Last 15',
    profile_record_win_short: 'W',
    profile_record_loss_short: 'L',
    profile_record_draw_short: 'D',
    tier_pawn: 'Pawn',
    tier_knight: 'Knight',
    tier_bishop: 'Bishop',
    tier_rook: 'Rook',
    tier_queen: 'Queen',
    tier_king: 'King',
    tier_emperor: 'Emperor',
    tier_unranked: 'Unranked',
    tier_modal_title: 'Rank System',
    tier_modal_intro: "Blundermate's rank system, based on Chess.com Rapid rating.",
    tier_range_open: '{min}+',
    tier_range_closed: '{min} – {max}',
    analysis_variation: 'Analyzing variation...',
    analysis_exploring: 'Exploring position...',
    analysis_loading: 'Loading...',
    sim_start: 'Start',
    input_placeholder: 'Paste PGN or FEN, or enter moves on the board',
    input_reset: 'Reset',
    filter_no_games: 'No games to show',
    time_min: '{n} min',
    time_sec: '{n}s',
  },
};

function detectLocale() {
  const stored = localStorage.getItem('locale');
  if (stored) return stored;
  if (navigator.language && navigator.language.startsWith('ko')) return 'ko';
  return 'en';
}

let locale = detectLocale();
export const t = (key) => STRINGS[locale]?.[key] ?? STRINGS['ko']?.[key] ?? key;
export const setLocale = (lang) => {
  locale = lang;
  localStorage.setItem('locale', lang);
};
export const getLocale = () => locale;
